# Generated by Django 5.2.7 on 2025-10-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Идентификатор'),
        ),
    ]
