# Generated by Django 5.2.7 on 2025-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_module', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Миниатюра'),
        ),
    ]
