# Generated by Django 5.2.7 on 2025-10-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos_module', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritecontact',
            unique_together={('user', 'contact')},
        ),
    ]
